"""
separate_with_lips.py
=====================
Visual‑guided speaker extraction pipeline (fully offline).

Given a noisy mixture (target + interferer + background noise) and a video
of the target speaker, this script:

  1. Loads a pre‑trained Conv‑TasNet model from a local folder.
  2. Separates the mixture into individual source signals.
  3. Computes a lip‑activity score for each video frame using LipScorer.
  4. For each separated source, computes its short‑time energy envelope
     and correlates it with the resampled lip‑activity signal.
  5. Selects the source with the highest correlation as the target speaker.
  6. Saves the extracted target speech as 'extracted_target.wav'.

Prerequisites:
  - my_video.mp4 in the project root (your short video facing the camera)
  - smoke_test_audio/mixture.wav (generated by create_mixture.py)
  - pretrained_models/sepformer-whamr16k/ (downloaded once, see README)

No internet access is required after the model has been downloaded.
"""

import os
import numpy as np
import torch
import soundfile as sf
from pathlib import Path
from scipy.io import wavfile
import cv2
from speechbrain.inference.separation import SepformerSeparation
from lip_scorer import LipScorer

# =============================================================================
# Project‑relative paths (works on any machine)
# =============================================================================
PROJECT_ROOT = Path(__file__).resolve().parent.parent

MIXTURE_PATH   = PROJECT_ROOT / "smoke_test_audio" / "mixture.wav"
VIDEO_PATH     = PROJECT_ROOT / "my_video.mp4"                  # your recording
OUTPUT_PATH    = PROJECT_ROOT / "smoke_test_audio" / "extracted_target.wav"
LOCAL_MODEL    = PROJECT_ROOT / "pretrained_models" / "sepformer-whamr16k"

SAMPLE_RATE    = 16000
ENERGY_HOP     = 160                           # 10 ms at 16 kHz → 100 fps

# =============================================================================
# Startup checks
# =============================================================================
if not MIXTURE_PATH.exists():
    raise FileNotFoundError(f"Mixture not found: {MIXTURE_PATH}")
if not VIDEO_PATH.exists():
    raise FileNotFoundError(f"Video not found: {VIDEO_PATH}")
if not os.path.isdir(LOCAL_MODEL):
    raise FileNotFoundError(f"Model directory not found: {LOCAL_MODEL}")

# =============================================================================
# Main pipeline
# =============================================================================
def main():
    # --- 1. Load separation model (local, no internet) ---
    print("Loading separation model from local cache ...")
    model = SepformerSeparation.from_hparams(
        source=LOCAL_MODEL,
        savedir=LOCAL_MODEL,
        hparams_file="hyperparams.yaml"
    )
    model.eval()
    print("Model ready.\n")

    # --- 2. Load and prepare mixture ---
    print("Separating mixture ...")
    mix_sr, mix_audio = wavfile.read(MIXTURE_PATH)

    # Convert to float32 in [-1, 1]
    if mix_audio.dtype == np.int16:
        mix_audio = mix_audio.astype(np.float32) / 32768.0
    else:
        mix_audio = mix_audio.astype(np.float32)

    # Force mono
    if mix_audio.ndim > 1:
        mix_audio = mix_audio.mean(axis=1)

    # Resample if needed (should already be 16 kHz)
    if mix_sr != SAMPLE_RATE:
        from scipy.signal import resample
        num_samples = int(len(mix_audio) * SAMPLE_RATE / mix_sr)
        mix_audio = resample(mix_audio, num_samples)

    # Create tensor (batch=1, time)
    mix_tensor = torch.from_numpy(mix_audio).float().unsqueeze(0)   # (1, T)
    print(f"   Mixture tensor shape: {mix_tensor.shape}")

    # --- 3. Separate and handle output shape ---
    est_sources = model.separate_batch(mix_tensor)   # (1, ???)
    est_sources = est_sources.squeeze(0).cpu().numpy()
    # Some models return (time, n_src); we want (n_src, time)
    if est_sources.ndim == 2 and est_sources.shape[0] > est_sources.shape[1]:
        est_sources = est_sources.T
    n_src = est_sources.shape[0]
    print(f"Obtained {n_src} separated sources.\n")

    # --- 4. Lip‑activity scoring ---
    print("Computing lip‑activity scores from video ...")
    scorer = LipScorer()
    lip_scores = scorer.process_video(str(VIDEO_PATH))

    # Get video frame rate
    cap = cv2.VideoCapture(str(VIDEO_PATH))
    video_fps = cap.get(cv2.CAP_PROP_FPS)
    cap.release()
    num_video_frames = len(lip_scores)
    print(f"Video FPS: {video_fps:.1f}, frames: {num_video_frames}, "
          f"duration: {num_video_frames/video_fps:.2f} s\n")

    # --- 5. Compute short‑time energy envelopes (manual, no librosa) ---
    print("Computing energy envelopes ...")

    def frame_energy(signal, frame_length, hop):
        """Root‑mean‑square energy per overlapping frame."""
        n_frames = 1 + (len(signal) - frame_length) // hop
        rms = np.zeros(n_frames)
        for j in range(n_frames):
            start = j * hop
            rms[j] = np.sqrt(np.mean(signal[start:start + frame_length] ** 2))
        return rms

    frame_len = int(0.025 * SAMPLE_RATE)   # 25 ms window
    energy_envelopes = []
    for i in range(n_src):
        rms = frame_energy(est_sources[i], frame_len, ENERGY_HOP)
        energy_envelopes.append(rms)

    # Time axes for audio (energy) and video (lip scores)
    t_audio = np.arange(len(energy_envelopes[0])) * (ENERGY_HOP / SAMPLE_RATE)
    t_video = np.arange(num_video_frames) / video_fps

    # --- 6. Resample lip scores to the audio time grid ---
    lip_at_audio = np.interp(t_audio, t_video, lip_scores)
    lip_at_audio = np.nan_to_num(lip_at_audio)

    # --- 7. Correlate each source's energy envelope with the lip signal ---
    print("Correlation with lip activity:")
    correlations = []
    for i in range(n_src):
        corr = np.corrcoef(energy_envelopes[i], lip_at_audio)[0, 1]
        correlations.append(corr)
        print(f"   Source {i+1}: correlation = {corr:.3f}")

    best_idx = np.argmax(correlations)
    print(f"\n--> Selected source {best_idx+1} as the target speaker.\n")

    # --- 8. Save extracted target speech ---
    target_audio = est_sources[best_idx].astype(np.float32)
    sf.write(str(OUTPUT_PATH), target_audio, SAMPLE_RATE)
    print(f"✅ Extracted target speech saved to '{OUTPUT_PATH}'")

if __name__ == "__main__":
    main()